version: '3.8'

services:
  omnibox:
    image: lampon/omnibox:latest
    container_name: omnibox
    ports:
      - "7123:7023"
    restart: unless-stopped
    volumes:
      - ./app/data:/app/data

volumes:
  omnibox-data: