version: '3.8'

services:
  omnibox:
    image: lampon/omnibox:latest
    container_name: omnibox
    ports:
      - "7123:7023"
    restart: unless-stopped
    environment:
      - PANSOU_URL=http://pansou:8888
    depends_on:
      - pansou
    volumes:
      - ./app/data:/app/data
    networks:
      - pansou-network
  pansou:
    image: ghcr.io/fish2018/pansou:latest
    container_name: pansou
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
      - CHANNELS=CosMM18,avpush,ribenseyuge1,cilitu,cctav,ppg1314,avab01,SeseAnime,QiangJAv,missavv,avwmjav,TGJAV,AVWUMAYUANPIAN,jpccav,PornXOS,CRAVWM12,MDFL88,madoua821,SanJiPian_HanGuo,sexlife520,CCCTAV,AVnew,tgsearchers3,Aliyun_4K_Movies,bdbdndn11,yunpanx,bsbdbfjfjff,yp123pan,sbsbsnsqq,yunpanxunlei,tianyifc,BaiduCloudDisk,txtyzy,peccxinpd,gotopan,PanjClub,kkxlzy,baicaoZY,MCPH01,bdwpzhpd,ysxb48,jdjdn1111,yggpan,MCPH086,zaihuayun,Q66Share,Oscar_4Kmovies,ucwpzy,shareAliyun,alyp_1,dianyingshare,Quark_Movies,XiangxiuNBB,ydypzyfx,ucquark,xx123pan,yingshifenxiang123,zyfb123,tyypzhpd,tianyirigeng,cloudtianyi,hdhhd21,Lsp115,oneonefivewpfx,qixingzhenren,taoxgzy,Channel_Shares_115,tyysypzypd,vip115hot,wp123zy,yunpan139,yunpan189,yunpanuc,yydf_hzl,leoziyuan,pikpakpan,Q_dongman,yoyokuakeduanju
      # 必须指定启用的插件，多个插件用逗号分隔
      - ENABLED_PLUGINS=bixin,cldi,clmao,clxiong,cyg,ddys,duoduo,erxiao,fox4k,haisou,hdmoli,hdr4k,huban,hunhepan,javdb,jikepan,jutoushe,labi,leijing,libvio,miaoso,muou,ouge,pan666,pansearch,panta,panwiki,panyq,pianku,qupansou,sdso,shandian,susu,thepiratebay,u3c3,wanou,wuji,xb6v,xdyh,xiaoji,xiaozhang,xuexizhinan,xys,yuhuage,zhizhen,djgou,nyaa,xinjuc,aikanzy,qupanshe,xdpan
      - CACHE_PATH=/app/cache
      - CACHE_MAX_SIZE=100
      - CACHE_TTL=60
      - ASYNC_PLUGIN_ENABLED=true
      - ASYNC_RESPONSE_TIMEOUT=4
      - ASYNC_MAX_BACKGROUND_WORKERS=20
      - ASYNC_MAX_BACKGROUND_TASKS=100
      - ASYNC_CACHE_TTL_HOURS=1
      # 如果需要代理，取消下面的注释并设置代理地址
      # - PROXY=socks5://127.0.0.1:7890
    volumes:
      - pansou-cache:/app/cache
    networks:
      - pansou-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8888/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # 如果需要代理，取消下面的注释
  # proxy:
  #   image: ghcr.io/snail007/goproxy:latest
  #   container_name: pansou-proxy
  #   restart: unless-stopped
  #   command: /proxy socks -p :7897
  #   networks:
  #     - pansou-network

volumes:
  omnibox-data:
  pansou-cache:
    name: pansou-cache
    external: true

networks:
  pansou-network:
    name: pansou-network
    external: true